/** @type {import('tailwindcss').Config} */
module.exports = {
    // WICHTIG: Hier scannt Tailwind deine Rust-Dateien
    content: ["./src/**/*.rs"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary-container": "#001a27",
                "on-primary-container": "#008abb",
                "on-primary": "#00354a",
                "primary-fixed-dim": "#7bd0ff",
                "on-primary-fixed-variant": "#004c69",
                "on-background": "#dae2fd",
                "tertiary-fixed-dim": "#4edea3",
                "on-surface": "#dae2fd",
                "tertiary-container": "#001c10",
                "on-tertiary-fixed": "#002113",
                "tertiary": "#4edea3",
                "on-tertiary": "#003824",
                "surface-container-lowest": "#060e20",
                "primary-fixed": "#c4e7ff",
                "on-surface-variant": "#c6c6cd",
                "on-error": "#690005",
                "on-secondary": "#213145",
                "on-error-container": "#ffdad6",
                "on-tertiary-container": "#009365",
                "error-container": "#93000a",
                "background": "#0b1326",
                "surface-tint": "#7bd0ff",
                "tertiary-fixed": "#6ffbbe",
                "on-primary-fixed": "#001e2c",
                "inverse-primary": "#00668a",
                "on-secondary-fixed": "#0b1c30",
                "on-secondary-container": "#a9bad3",
                "inverse-surface": "#dae2fd",
                "surface-variant": "#2d3449",
                "outline": "#909097",
                "on-tertiary-fixed-variant": "#005236",
                "surface-container-high": "#222a3d",
                "surface-dim": "#0b1326",
                "secondary-fixed-dim": "#b7c8e1",
                "secondary-container": "#3a4a5f",
                "error": "#ffb4ab",
                "surface-container-highest": "#2d3449",
                "primary": "#7bd0ff",
                "secondary-fixed": "#d3e4fe",
                "outline-variant": "#45464d",
                "surface-container": "#171f33",
                "surface-bright": "#31394d",
                "on-secondary-fixed-variant": "#38485d",
                "inverse-on-surface": "#283044",
                "surface": "#0b1326",
                "secondary": "#b7c8e1",
                "surface-container-low": "#131b2e"
            },
            fontFamily: {
                "headline": ["Space Grotesk"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
        },
    },
    plugins: [],
}